[package]
name = "vetkd-notes-canister"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]


[dependencies]
candid = "0.10.13"
ic-cdk = "0.17.1"
ic-cdk-macros = "0.17.1"
ic-stable-structures = "0.6.7"
lazy_static = "1.5.0"
serde_json = "1.0.138"
anyhow = "1.0.95"
serde = "1.0.217"
ic-types = "0.7.0"
hex = "0.4.3"
chrono = "0.4.39"
ic-vetkd-notes = { path = "../vetkd-notes" }
