
[package]
name = "vetkd-notes"
version = "0.1.0"
edition = "2021"
exclude = [ "package.json", "node_modules", ".turbo", "turbo.json" ]

[dependencies]
candid = "0.9.11"
ic-cdk = "0.11.3"
ic-cdk-macros = "0.8.1"
ic-stable-structures = "0.6.4"
lazy_static = "1.4.0"
serde_json = "1.0.133"
anyhow = "1.0.75"
serde = "1.0.190"
ic-types = "0.7.0"
hex = "0.4.3"
