name: "Build"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: compile-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ðŸš€ Run release-please
        uses: googleapis/release-please-action@v4
        id: release-please
        with:
          config-file: .github/release-please-config.json # âœ… Explicitly specify the config file
          manifest-file: .github/release-please-manifest.json
      
      - name: ðŸ—ï¸ Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            target: wasm32-unknown-unknown
            toolchain: stable
            components: rustfmt, clippy

      - name: Install wasm-pack
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev
          cargo install wasm-pack
          cargo install candid-extractor

      - name: ðŸ—ï¸ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.12.3"
      
      - name: ðŸ—ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.0.0'
          cache: 'pnpm'

      - name: ðŸ—ï¸ Install dependencies
        run: pnpm install
    
      - name: ðŸ—ï¸ Build
        run: pnpm build:release

      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v5
      
      - name: Clean docs folder
        run: cargo clean --doc
      
      - name: Build docs
        run: |
          pnpm doc
          find docs
      
      - name: Cargo publish
        if: ${{ steps.release-please.outputs['packages/vetkd-notes--release_created'] }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --package ic-vetkd-notes

      - name: NPM publish
        if: ${{ steps.release-please.outputs['packages/vetkd-notes-client--release_created'] }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ./.npmrc
          pnpm publish --access public --filter "@shipstone-labs/ic-vetkd-notes-client" --no-git-checks

      - name: Upload artifact
        if: ${{ steps.release-please.outputs.releases_created }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        if: ${{ steps.release-please.outputs.releases_created }}
        uses: actions/deploy-pages@v4